### ISSUE TITLE
Error when "closing" a time interval

### ISSUE THREAD

**Issue by caxelrud** [ReactiveBayes/Rocket.jl#52]
I am getting the following error:
```
source = interval(10000)
close(source) 
ERROR: MethodError: no method matching close(::TimerObservable{Int64})
```

**Comment by bvdmitri** [comment]
The `close` function is not (and should not be) implemented for `interval` because there is nothing to `close` initially. The interval only starts when you call `subscribe!`

```julia
source = interval(10000)
```

This line merely sets up the data structure needed for `subscribe!.` The interval begins with the following line:

```julia
subscription = subscribe!(source, logger()) # starts the interval
```

You can then use `unsubscribe! `to stop the interval, which will automatically call `close`:

```julia
unsubscribe!(subscription)  # Automatically closes the interval
```
